# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert IP addresses in dotted-decimal notation to long integers
#'
#' @param ip input character vector
#' @return vector of equivalent long integer IP addresses
ip2long <- function(ip) {
    .Call('ipv4heatmap_ip2long', PACKAGE = 'ipv4heatmap', ip)
}

#' Convert IP addresses in long integer format to dotted-decimal notation
#'
#' @param ip input numeric (long int) vector
#' @return vector of equivalent dotted-decimal IP addresses
long2ip <- function(ip) {
    .Call('ipv4heatmap_long2ip', PACKAGE = 'ipv4heatmap', ip)
}

ipv4matrix <- function(ip) {
    .Call('ipv4heatmap_ipv4matrix', PACKAGE = 'ipv4heatmap', ip)
}

