# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Character (dotted-decimal) IPv4 Address Conversion to long integer
#'
#' Convert IP addresses in character (dotted-decimal) notation to long integers
#'
#' @param ip input character vector of IPv4 addresses (dotted-decimal)
#' @return vector of equivalent long integer IP addresses
#' @examples
#' ip2long("24.0.5.11")
#' ip2long(c("24.0.5.11", "211.3.77.96"))
ip2long <- function(ip) {
    .Call('ipv4heatmap_ip2long', PACKAGE = 'ipv4heatmap', ip)
}

#' Intger IPv4 Address Conversion to Character
#'
#' Converts IP addresses in long integer format to character (dotted-decimal) notation
#'
#' @param ip input numeric (long integer) vector
#' @return vector of equivalent character (dotted-decimal) IP addresses
#' @examples
#' long2ip(402654475)
#' long2ip(c(402654475, 3540208992))
long2ip <- function(ip) {
    .Call('ipv4heatmap_long2ip', PACKAGE = 'ipv4heatmap', ip)
}

#' IPv4 Hilbert Curve Matrix
#'
#' Returns a 4096x4096 Hilbert curve matrix for an input vector of IP addresses. Generally not called directly (most of the time you'll want to use \code{ipv4heatmap}), but avilable in the event another method of visualization is necessary/desired.
#'
#' @param ip input character (dotted-deciman IPv4s) vector
#' @return 4096x4096 matrix, with non-0 entries being the count of IP addresses in that netblock
ipv4matrix <- function(ip) {
    .Call('ipv4heatmap_ipv4matrix', PACKAGE = 'ipv4heatmap', ip)
}

#' Bounding box from CIDR blocks
#'
#' Returns a \code{list} of bounding boxes for a given CIDR within the Hilbert-curve plane
#'
#' @param cidr character vector of dotted-decimal/digit CIDRs
#' @return list of bounding box extents for each CIDR - \code{cidr}, \code{xmin}, \code{ymin}, \code{xmax}, \code{ymax}
#' @examples
#' boundingBoxFromCIDR("30.0.0.0/8")
boundingBoxFromCIDR <- function(cidr) {
    .Call('ipv4heatmap_boundingBoxFromCIDR', PACKAGE = 'ipv4heatmap', cidr)
}

